export let furniture = {
   [KARGO]: new FurnitureItem(KARGO, 98833, furnitureManufacturer2),
   [SINK]: new FurnitureItem(SINK, '', ''),
   [DISH]: new FurnitureItem(DISH, 60765, furnitureManufacturer8),
   [LEGS]: new FurnitureItem(LEGS, 57412, furnitureManufacturer4),
   [LEGS_CLIPS]: new FurnitureItem(LEGS_CLIPS, 87322, furnitureManufacturer4),
   [PUSH]: new FurnitureItem(PUSH, 13592, furnitureManufacturer2),
   [PUSH_BAR]: new FurnitureItem(PUSH_BAR, 13596, furnitureManufacturer2),
   [PLINTH_SEAL]: new FurnitureItem(PLINTH_SEAL, 81885, furnitureManufacturer5, 3),
   [HOOKS_RIGHT]: new FurnitureItem(HOOKS_RIGHT, 59642, furnitureManufacturer6),
   [HOOKS_LEFT]: new FurnitureItem(HOOKS_LEFT, 59640, furnitureManufacturer6),
   [RAIL]: new FurnitureItem(RAIL, 52680, furnitureManufacturer2, 2),
   [OPENING_LIMITER]: new FurnitureItem(OPENING_LIMITER, 31837, furnitureManufacturer7),
   [LATTICE]: new FurnitureItem(LATTICE, 87377, furnitureManufacturer9),
   [ABSORBER]: new FurnitureItem(ABSORBER, 80399, furnitureManufacturer8),
   [CONNECTION_BAR]: new FurnitureItem(CONNECTION_BAR, 82308, furnitureManufacturer8),
   [CONFIRMATS]: new FurnitureItem(CONFIRMATS, 52559, furnitureManufacturer8),
   [SHELF_HOLDER]: new FurnitureItem(SHELF_HOLDER, 52636, furnitureManufacturer8),
   [SELF_TAPPING_15]: new FurnitureItem(SELF_TAPPING_15, 11358, furnitureManufacturer2),
   [SELF_TAPPING_30]: new FurnitureItem(SELF_TAPPING_30, 11360, furnitureManufacturer2),
   [SCREW_40]: new FurnitureItem(SCREW_40, 52600, furnitureManufacturer8),
   [MINIFIX]: new FurnitureItem(MINIFIX, 61281, furnitureManufacturer1),
   [MINIFIX_DOWEL]: new FurnitureItem(MINIFIX_DOWEL, 57722, furnitureManufacturer1),
   [LED_PROFILE]: new FurnitureItem(LED_PROFILE, '', furnitureManufacturer11, 2),
   [LED_DIFFUSER]: new FurnitureItem(LED_DIFFUSER, '', furnitureManufacturer11, 2),
   [LED_STRIP]: new FurnitureItem(LED_STRIP, '', furnitureManufacturer10),
   [POWER_UNIT]: new FurnitureItem(POWER_UNIT, '', furnitureManufacturer12),
   [SWITCH]: new FurnitureItem(SWITCH, 86470, furnitureManufacturer10),
   [HANDLE]: new FurnitureItem(HANDLE, '', ''),
   [GOLA_L]: new FurnitureItem(GOLA_L, '', furnitureManufacturer4, 4),
   [GOLA_C]: new FurnitureItem(GOLA_C, '', furnitureManufacturer4, 4),
   [LIFT]: new FurnitureItem(LIFT, 12365, furnitureManufacturer2),
   [TABLETOP_CONNECTOR]: new FurnitureItem(TABLETOP_CONNECTOR, 52667, furnitureManufacturer8),
   [HOOKS_RIGHT_CUP]: new FurnitureItem(HOOKS_RIGHT_CUP, 59649, furnitureManufacturer6),
   [HOOKS_LEFT_CUP]: new FurnitureItem(HOOKS_LEFT_CUP, 59647, furnitureManufacturer6),
}

// https://viyar.ua/ua/search/?q=29445